# Generated by Django 3.0.8 on 2020-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='emailverified',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
