# Generated by Django 3.0.8 on 2020-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_emailverified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='users',
            name='emailverified',
            field=models.BooleanField(default=False),
        ),
    ]
