# Generated by Django 3.0.8 on 2020-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200728_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_method',
            field=models.CharField(choices=[('userid', 'userid'), ('kakao', 'Kakao'), ('kakao', 'google')], default='userid', max_length=50),
        ),
    ]
