# Generated by Django 3.0.8 on 2020-07-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200729_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login_method',
            field=models.CharField(choices=[('user', 'user'), ('kakao', 'Kakao'), ('kakao', 'google')], default='user', max_length=50),
        ),
    ]
