# Generated by Django 3.0.7 on 2020-07-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinct_product',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Genre_Category'),
        ),
        migrations.AlterField(
            model_name='distinct_product',
            name='line_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Line_Category'),
        ),
        migrations.AlterField(
            model_name='distinct_product',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Menu'),
        ),
        migrations.AlterField(
            model_name='distinct_product',
            name='online_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Online_Category'),
        ),
        migrations.AlterField(
            model_name='distinct_product',
            name='skin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Skin_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Genre_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Line_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Online_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Skin_Category'),
        ),
    ]
