# Generated by Django 3.0.7 on 2020-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200727_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distinct_product',
            name='star',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.AddField(
            model_name='product',
            name='star_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Product_Star',
        ),
    ]
