# Generated by Django 3.0.7 on 2020-07-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200722_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('image_url1', models.CharField(max_length=1000)),
                ('image_url2', models.CharField(max_length=1000)),
                ('image_url3', models.CharField(max_length=1000)),
                ('image_url4', models.CharField(max_length=1000)),
                ('detail_html', models.CharField(max_length=10000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
    ]
