# Generated by Django 3.0.7 on 2020-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='detail_html',
            field=models.TextField(max_length=10000),
        ),
    ]
