# Generated by Django 3.0.7 on 2020-07-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200723_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_review_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Product_Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_star',
            },
        ),
        migrations.CreateModel(
            name='Product_Plag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_sale', models.CharField(max_length=10)),
                ('flag_gift', models.CharField(max_length=10)),
                ('flag_new', models.CharField(max_length=10)),
                ('flag_best', models.CharField(max_length=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_flag',
            },
        ),
    ]
