# Generated by Django 3.0.7 on 2020-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200724_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_review_url',
            field=models.TextField(default='', max_length=200),
        ),
    ]
