# Generated by Django 3.0.7 on 2020-07-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200724_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star', to='products.Product_Star'),
        ),
    ]
